### ISSUE TITLE
how to use glb file on markdown?

### ISSUE THREAD

**Issue by Hankyu-Kim** [swift502/Web#12]
How to use modelviewer for glb file on markdown?

Hi I m noob at astro and try to import glb file on markdown(post).

I installed  like below :
```
npm install three @react-three/fiber @react-three/drei
npm install @google/model-viewer
```

here is the error:

> [ERROR] [MissingImageDimension] Missing width and height attributes for /src/assets/navya.glb. When using remote images, both dimensions are required unless in order to avoid CLS.
>   Hint:
>     If your image is inside your src folder, you probably meant to import it instead. See the Imports guide for more information https://docs.astro.build/en/guides/imports/#other-assets. You can also use inferSize={true} for remote images to get the original dimensions.
>   Error reference:
>     https://docs.astro.build/en/reference/errors/missing-image-dimension/
>   Stack trace:

can you help?

+ do i need vite plugin for this?

**Comment by swift502** [comment]
@Hankyu-Kim Hi.
I'm afraid I have no idea what you're trying to achieve.
The idea that you can put GLBs in markdown is news to me, personally. Never done it, no idea how to do it, no idea what astro would have to do with it.

I always follow the model viewer docs to put models on my website. That's the only thing I can suggest to you. 🙏
https://modelviewer.dev

**Comment by swift502** [comment]
At best I can imagine using MDX to insert custom components in your mdx files.

So maybe an mdx which imports a custom astro component. That astro component would be importing and rendering the model viewer. And just pass the model name as a parameter for the astro component.

**Comment by Hankyu-Kim** [comment]
Oh I though you re using .glb file, but now I got you re using .hdr file for 3d image.
and also realized you using model viewer on index.astro

I have only .fbx, .usdx, .glTF, and .glb file,
but I'll try the same like you did since your web page work perfectly!
Thank you for reply, tho!

**Comment by swift502** [comment]
No bro. I am using a .glb file. Hdr is used for lighting the model. I load models in my index dynamically using JS, because they're random.

**PLEASE read the model-viewer documentation**:
https://modelviewer.dev
https://modelviewer.dev/examples/loading/#glbModel

They have simple examples of how to load a model. You don't have to reverse engineer my site, read the docs and gradually build up to what you need.

---

Going back to what I understand you want, loading models in markdown, I still believe MDX is a good idea.
I asked ChatGPT how to do it. It would be something like this, it's quite elegant.

### ChatGPT response

Rendering a `.glb` file using Astro components, MDX, and Google's `<model-viewer>` can be done by following these steps:

1. **Set up your Astro project**: If you haven't already, create a new Astro project.

2. **Install necessary dependencies**: Ensure you have the necessary packages installed. You'll need `@astrojs/mdx` for MDX support.

   ```bash
   npm install @astrojs/mdx
   ```

3. **Configure Astro to use MDX**: Update your `astro.config.mjs` to include the MDX integration.

   ```javascript
   import { defineConfig } from 'astro/config';
   import mdx from '@astrojs/mdx';

   export default defineConfig({
     integrations: [mdx()],
   });
   ```

4. **Add Google's Model-Viewer**: Include the Model-Viewer script in your project. You can add this in your `public/index.html` or in a layout component.

   ```html
   <script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"></script>
   ```

5. **Create a component for the model**: Create an Astro component that uses `<model-viewer>`. For example, create `src/components/ModelViewer.astro`.

   ```jsx
   ---
    // Import the component
    const modelSrc = Astro.props.src;
    ---
    <model-viewer 
      src={modelSrc} 
      alt="A 3D model" 
      auto-rotate 
      camera-controls 
      style="width: 100%; height: 100%;"
    ></model-viewer>
   ```

6. **Create an MDX file**: Create an MDX file where you want to render the model, e.g., `src/pages/model.mdx`.

   ```mdx
   ---
   title: "3D Model"
   ---

   import ModelViewer from '../components/ModelViewer.astro';

   # My 3D Model

   This is an example of a 3D model rendered using Google's Model-Viewer.

   <ModelViewer src="/path/to/your/model.glb" />
   ```

7. **Add the model file**: Place your `.glb` file in the appropriate directory within the `public` folder of your project, e.g., `public/models/myModel.glb`.

8. **Run the project**: Start your Astro development server to see the rendered model.

   ```bash
   npm run dev
   ```

Putting it all together, your project structure might look like this:

```
astro-project/
│
├── public/
│   ├── index.html
│   └── models/
│       └── myModel.glb
│
├── src/
│   ├── components/
│   │   └── ModelViewer.astro
│   └── pages/
│       └── model.mdx
│
├── astro.config.mjs
└── package.json
```

This setup will render the `.glb` model using Astro components, MDX, and Google's Model-Viewer in an Astro project.

**Comment by swift502** [comment]
I wish you good luck, though you're making something simple very complicated.

You don't need vite plugins, react or three for any of this.

**Comment by Hankyu-Kim** [comment]
Thanks swift502!
I made it!
[https://hankyukim.com/posts/navya/](https://hankyukim.com/posts/navya/)
